In [29]:
import cv2

In [1]:
# !pip install opencv-python

In [7]:
# !pip uninstall opencv-python

Found existing installation: opencv-python 4.3.0.36
Uninstalling opencv-python-4.3.0.36:
  Would remove:
    /home/bitai/anaconda3/lib/python3.7/site-packages/opencv_python-4.3.0.36.dist-info/*
    /home/bitai/anaconda3/lib/python3.7/site-packages/opencv_python.libs/libQtCore-6b7bca35.so.4.8.7
    /home/bitai/anaconda3/lib/python3.7/site-packages/opencv_python.libs/libQtGui-a00f4bbc.so.4.8.7
    /home/bitai/anaconda3/lib/python3.7/site-packages/opencv_python.libs/libQtTest-6d3ddc1c.so.4.8.7
    /home/bitai/anaconda3/lib/python3.7/site-packages/opencv_python.libs/libXcursor-1a09904e.so.1.0.2
    /home/bitai/anaconda3/lib/python3.7/site-packages/opencv_python.libs/libXfixes-d274cb03.so.3.1.0
    /home/bitai/anaconda3/lib/python3.7/site-packages/opencv_python.libs/libXi-e28fba09.so.6.1.0
    /home/bitai/anaconda3/lib/python3.7/site-packages/opencv_python.libs/libXinerama-b7a62e01.so.1.0.0
    /home/bitai/anaconda3/lib/python3.7/site-packages/opencv_python.libs/libXrandr-1b5fae8f.so.2.2.0


In [24]:
import cv2

In [27]:
help(cv2)

Help on package cv2:

NAME
    cv2

PACKAGE CONTENTS


FILE
    (built-in)




In [28]:
print(cv2.__version__)

4.3.0


In [1]:
import cv2

In [2]:
print(cv2.__version__)

4.3.0


In [3]:
import numpy as np

In [5]:
img = np.random.randint(0,10,(7,7))

print(img)

[[4 4 1 9 0 9 4]
 [9 1 8 3 1 3 2]
 [2 7 2 6 5 1 8]
 [8 0 7 6 7 7 1]
 [7 0 3 8 6 6 3]
 [9 1 5 0 8 6 2]
 [1 9 2 2 0 4 2]]


In [6]:
img_np = np.ones([7,7])
print(img_np)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [8]:
kernel = np.array([-1, 0, 1 ])
print(kernel)

[-1  0  1]


In [14]:
print(type(kernel))
print(type(img_np))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [18]:
img_cv = cv2.resize(img_np, (7,7))
                    
print(img_cv)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [17]:
kernel = cv2.resize(kernel, (1, 3))
print(kernel)

[[-1]
 [ 0]
 [ 1]]


In [21]:
print(type(img_cv))
print(type(kernel))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [25]:
conv_test = cv2.filter2D(img_cv, -1 , kernel)

print(conv_test)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  2.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [30]:
print(kernel)

[[-1]
 [ 0]
 [ 1]]


In [26]:
print(img_cv)

[[0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 2. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 3.]]


In [24]:
img_cv[0][0] = 0
img_cv[3][3] = 2
img_cv[6][6] = 3

# filter2D - Convolution이 결국
# 라플라스 변환과 푸리에 변환에 관계를 가지고 있기 때문이다.
conv_test = cv2.filter2D(img_cv, -1, kernel)

print(conv_test)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  2.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [27]:
# sudo apt-get install ctags cscope

In [ ]:
# 라플라스 변환 -> 전달 함수를 얻기 위해 계산함
# 입력 대 출력비를 구하겠다.
# 입력이 10, 출력이 7, 입출력비: 7/10
# 입력이 y'' = y' +3y +2
# 출력이 y' = 3e^3x => y= e^3x
# 라플라스 변환 통해 입출력비를 게산할 수 있게 된다.
# integral 0 ~ inf f(t)e^-st dt

# Low Pass Filter(LPF 설계법) - 1D Convolution
# 전달함수 -> 실ㄹ제 값을 필터링 하는 방법.

In [1]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPool2D, Flatten, Dense

In [2]:
classifier = Sequential()
classifier.add(
    Conv2D(
        32, (3, 3), 
        input_shape = (64, 64, 3), 
        activation = 'relu'
    )
)
classifier.add(
    Conv2D(
        32, (3, 3), 
        activation = 'relu'
    )
)
classifier.add(
    Conv2D(
        32, (3, 3), 
        activation = 'relu'
    )
)
classifier.add(MaxPool2D(pool_size = (2, 2)))
classifier.add(MaxPool2D(pool_size = (2, 2)))
classifier.add(Flatten())

In [3]:
classifier.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 62, 62, 32)        896       
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 60, 60, 32)        9248      
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 58, 58, 32)        9248      
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 29, 29, 32)        0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 14, 14, 32)        0         
_________________________________________________________________
flatten (Flatten)            (None, 6272)              0         
Total params: 19,392
Trainable params: 19,392
Non-trainable params: 0
____________________________________________________

In [4]:
classifier.add(Dense(128, activation='relu'))
# classifier.add(Dense(128, activation='relu'))
# classifier.add(Dense(128, activation='relu'))
# classifier.add(Dense(128, activation='relu'))
classifier.add(Dense(1, activation= 'sigmoid'))
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [5]:
from keras.preprocessing.image import ImageDataGenerator

train_gen = ImageDataGenerator(
    rescale = 1.0 / 255,
    shear_range = 0.2,
    zoom_range = 0.2,
    horizontal_flip = True
)

test_gen = ImageDataGenerator(rescale = 1.0 / 255)

In [6]:
!ls Applied-Deep-Learning-with-Keras/Lesson07/Datasets/dataset/training_set

cats  dogs


In [7]:
trainSet = train_gen.flow_from_directory(
    'Applied-Deep-Learning-with-Keras/Lesson07/' +
    'Datasets/dataset/training_set',
    target_size = (64, 64),
    batch_size = 32,
    class_mode = 'binary'
)
testSet = test_gen.flow_from_directory(
    'Applied-Deep-Learning-with-Keras/Lesson07/' +
    'Datasets/dataset/test_set',
    target_size = (64, 64),
    batch_size = 32,
    class_mode = 'binary'
)

Found 20000 images belonging to 2 classes.
Found 5000 images belonging to 2 classes.


In [12]:
batch_size = 100

classifier.fit_generator(
    trainSet,
    steps_per_epoch = int(10000/batch_size),
    epochs = 200,
    validation_data = testSet,
    validation_steps = int(2500/batch_size)
)

Epoch 1/200
100/100 [==============================] - 13s 129ms/step - loss: 0.2048 - accuracy: 0.9144 - val_loss: 0.4682 - val_accuracy: 0.8150
Epoch 2/200
100/100 [==============================] - 13s 129ms/step - loss: 0.1828 - accuracy: 0.9225 - val_loss: 0.4429 - val_accuracy: 0.8388
Epoch 3/200
100/100 [==============================] - 13s 129ms/step - loss: 0.1829 - accuracy: 0.9275 - val_loss: 0.3459 - val_accuracy: 0.8750
Epoch 4/200
100/100 [==============================] - 13s 128ms/step - loss: 0.1936 - accuracy: 0.9247 - val_loss: 0.4965 - val_accuracy: 0.8200
Epoch 5/200
100/100 [==============================] - 13s 130ms/step - loss: 0.1920 - accuracy: 0.9156 - val_loss: 0.4089 - val_accuracy: 0.8462
Epoch 6/200
100/100 [==============================] - 13s 129ms/step - loss: 0.1843 - accuracy: 0.9237 - val_loss: 0.4388 - val_accuracy: 0.8288
Epoch 7/200
100/100 [==============================] - 13s 129ms/step - loss: 0.2065 - accuracy: 0.9175 - val_loss: 0.3865 -

Epoch 57/200
100/100 [==============================] - 13s 132ms/step - loss: 0.1428 - accuracy: 0.9444 - val_loss: 0.4306 - val_accuracy: 0.8662
Epoch 58/200
100/100 [==============================] - 13s 129ms/step - loss: 0.1634 - accuracy: 0.9353 - val_loss: 0.4685 - val_accuracy: 0.8275
Epoch 59/200
100/100 [==============================] - 13s 128ms/step - loss: 0.1599 - accuracy: 0.9353 - val_loss: 0.4763 - val_accuracy: 0.8325
Epoch 60/200
100/100 [==============================] - 13s 128ms/step - loss: 0.1382 - accuracy: 0.9463 - val_loss: 0.5148 - val_accuracy: 0.8462
Epoch 61/200
100/100 [==============================] - 13s 130ms/step - loss: 0.1506 - accuracy: 0.9453 - val_loss: 0.3873 - val_accuracy: 0.8637
Epoch 62/200
100/100 [==============================] - 13s 128ms/step - loss: 0.1563 - accuracy: 0.9406 - val_loss: 0.5517 - val_accuracy: 0.8325
Epoch 63/200
100/100 [==============================] - 13s 128ms/step - loss: 0.1495 - accuracy: 0.9400 - val_loss: 0

100/100 [==============================] - 13s 128ms/step - loss: 0.1263 - accuracy: 0.9494 - val_loss: 0.4340 - val_accuracy: 0.8675
Epoch 113/200
100/100 [==============================] - 13s 129ms/step - loss: 0.1264 - accuracy: 0.9466 - val_loss: 0.5296 - val_accuracy: 0.8450
Epoch 114/200
100/100 [==============================] - 13s 128ms/step - loss: 0.1365 - accuracy: 0.9456 - val_loss: 0.4592 - val_accuracy: 0.8600
Epoch 115/200
100/100 [==============================] - 13s 128ms/step - loss: 0.1384 - accuracy: 0.9434 - val_loss: 0.4833 - val_accuracy: 0.8462
Epoch 116/200
100/100 [==============================] - 13s 128ms/step - loss: 0.1282 - accuracy: 0.9522 - val_loss: 0.5146 - val_accuracy: 0.8400
Epoch 117/200
100/100 [==============================] - 13s 129ms/step - loss: 0.1162 - accuracy: 0.9541 - val_loss: 0.4106 - val_accuracy: 0.8675
Epoch 118/200
100/100 [==============================] - 13s 128ms/step - loss: 0.1229 - accuracy: 0.9528 - val_loss: 0.5804 -

100/100 [==============================] - 12s 125ms/step - loss: 0.1125 - accuracy: 0.9600 - val_loss: 0.6433 - val_accuracy: 0.8375
Epoch 168/200
100/100 [==============================] - 13s 126ms/step - loss: 0.0929 - accuracy: 0.9675 - val_loss: 0.5624 - val_accuracy: 0.8525
Epoch 169/200
100/100 [==============================] - 13s 126ms/step - loss: 0.0942 - accuracy: 0.9666 - val_loss: 0.5978 - val_accuracy: 0.8350
Epoch 170/200
100/100 [==============================] - 13s 126ms/step - loss: 0.0855 - accuracy: 0.9656 - val_loss: 0.5666 - val_accuracy: 0.8487
Epoch 171/200
100/100 [==============================] - 13s 126ms/step - loss: 0.1256 - accuracy: 0.9509 - val_loss: 0.5528 - val_accuracy: 0.8462
Epoch 172/200
100/100 [==============================] - 13s 129ms/step - loss: 0.1017 - accuracy: 0.9613 - val_loss: 0.6142 - val_accuracy: 0.8350
Epoch 173/200
100/100 [==============================] - 13s 128ms/step - loss: 0.1110 - accuracy: 0.9553 - val_loss: 0.5249 -

In [13]:
import numpy as np

from keras.preprocessing import image

In [14]:
new_image = image.load_img(
    'test_image_2.jpg',
    target_size = (64, 64)
)

In [15]:
new_image = image.img_to_array(new_image)
new_image = np.expand_dims(new_image, axis = 0)

result = classifier.predict(new_image)
#trainSet.class_indices

if result[0][0] == 1:
    prediction = 'Dog'
else:
    prediction = 'Cat'
    
print(prediction)

Cat
