In [29]:
import cv2

In [1]:
# !pip install opencv-python

In [7]:
# !pip uninstall opencv-python

Found existing installation: opencv-python 4.3.0.36
Uninstalling opencv-python-4.3.0.36:
  Would remove:
    /home/bitai/anaconda3/lib/python3.7/site-packages/opencv_python-4.3.0.36.dist-info/*
    /home/bitai/anaconda3/lib/python3.7/site-packages/opencv_python.libs/libQtCore-6b7bca35.so.4.8.7
    /home/bitai/anaconda3/lib/python3.7/site-packages/opencv_python.libs/libQtGui-a00f4bbc.so.4.8.7
    /home/bitai/anaconda3/lib/python3.7/site-packages/opencv_python.libs/libQtTest-6d3ddc1c.so.4.8.7
    /home/bitai/anaconda3/lib/python3.7/site-packages/opencv_python.libs/libXcursor-1a09904e.so.1.0.2
    /home/bitai/anaconda3/lib/python3.7/site-packages/opencv_python.libs/libXfixes-d274cb03.so.3.1.0
    /home/bitai/anaconda3/lib/python3.7/site-packages/opencv_python.libs/libXi-e28fba09.so.6.1.0
    /home/bitai/anaconda3/lib/python3.7/site-packages/opencv_python.libs/libXinerama-b7a62e01.so.1.0.0
    /home/bitai/anaconda3/lib/python3.7/site-packages/opencv_python.libs/libXrandr-1b5fae8f.so.2.2.0


In [24]:
import cv2

In [27]:
help(cv2)

Help on package cv2:

NAME
    cv2

PACKAGE CONTENTS


FILE
    (built-in)




In [28]:
print(cv2.__version__)

4.3.0


In [1]:
import cv2

In [2]:
print(cv2.__version__)

4.3.0


In [3]:
import numpy as np

In [5]:
img = np.random.randint(0,10,(7,7))

print(img)

[[4 4 1 9 0 9 4]
 [9 1 8 3 1 3 2]
 [2 7 2 6 5 1 8]
 [8 0 7 6 7 7 1]
 [7 0 3 8 6 6 3]
 [9 1 5 0 8 6 2]
 [1 9 2 2 0 4 2]]


In [6]:
img_np = np.ones([7,7])
print(img_np)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [8]:
kernel = np.array([-1, 0, 1 ])
print(kernel)

[-1  0  1]


In [14]:
print(type(kernel))
print(type(img_np))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [18]:
img_cv = cv2.resize(img_np, (7,7))
                    
print(img_cv)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [17]:
kernel = cv2.resize(kernel, (1, 3))
print(kernel)

[[-1]
 [ 0]
 [ 1]]


In [21]:
print(type(img_cv))
print(type(kernel))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [25]:
conv_test = cv2.filter2D(img_cv, -1 , kernel)

print(conv_test)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  2.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [30]:
print(kernel)

[[-1]
 [ 0]
 [ 1]]


In [26]:
print(img_cv)

[[0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 2. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 3.]]


In [24]:
img_cv[0][0] = 0
img_cv[3][3] = 2
img_cv[6][6] = 3

# filter2D - Convolution이 결국
# 라플라스 변환과 푸리에 변환에 관계를 가지고 있기 때문이다.
conv_test = cv2.filter2D(img_cv, -1, kernel)

print(conv_test)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  2.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [27]:
# sudo apt-get install ctags cscope

In [ ]:
# 라플라스 변환 -> 전달 함수를 얻기 위해 계산함
# 입력 대 출력비를 구하겠다.
# 입력이 10, 출력이 7, 입출력비: 7/10
# 입력이 y'' = y' +3y +2
# 출력이 y' = 3e^3x => y= e^3x
# 라플라스 변환 통해 입출력비를 게산할 수 있게 된다.
# integral 0 ~ inf f(t)e^-st dt

# Low Pass Filter(LPF 설계법) - 1D Convolution
# 전달함수 -> 실ㄹ제 값을 필터링 하는 방법.

In [11]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPool2D, Flatten, Dense

In [26]:
classifier = Sequential()
classifier.add(
    Conv2D(
        32, (3, 3), 
        input_shape = (64, 64, 3), 
        activation = 'relu'
    )
)
classifier.add(
    Conv2D(
        32, (3, 3), 
        activation = 'relu'
    )
)
classifier.add(
    Conv2D(
        32, (3, 3), 
        activation = 'relu'
    )
)
classifier.add(MaxPool2D(pool_size = (2, 2)))
classifier.add(MaxPool2D(pool_size = (2, 2)))
classifier.add(Flatten())

In [27]:
classifier.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_6 (Conv2D)            (None, 62, 62, 32)        896       
_________________________________________________________________
conv2d_7 (Conv2D)            (None, 60, 60, 32)        9248      
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 58, 58, 32)        9248      
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 29, 29, 32)        0         
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 14, 14, 32)        0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 6272)              0         
Total params: 19,392
Trainable params: 19,392
Non-trainable params: 0
__________________________________________________

In [28]:
classifier.add(
    Dense(128, activation = 'relu')
)
classifier.add(
    Dense(128, activation = 'relu')
)
classifier.add(
    Dense(128, activation = 'relu')
)
classifier.add(
    Dense(128, activation = 'relu')
)
classifier.add(
    Dense(1, activation = 'softmax')
)

classifier.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)

In [29]:
from keras.preprocessing.image import ImageDataGenerator

train_gen = ImageDataGenerator(
    rescale = 1.0 / 255,
    shear_range = 0.2,
    zoom_range = 0.2,
    horizontal_flip = True
)

test_gen = ImageDataGenerator(rescale = 1.0 / 255)

In [30]:
!ls Applied-Deep-Learning-with-Keras/Lesson07/Datasets/dataset/training_set

cats  dogs


In [31]:
trainSet = train_gen.flow_from_directory(
    'Applied-Deep-Learning-with-Keras/Lesson07/' +
    'Datasets/dataset/training_set',
    target_size = (64, 64),
    batch_size = 32,
    class_mode = 'binary'
)
testSet = test_gen.flow_from_directory(
    'Applied-Deep-Learning-with-Keras/Lesson07/' +
    'Datasets/dataset/test_set',
    target_size = (64, 64),
    batch_size = 32,
    class_mode = 'binary'
)

Found 20000 images belonging to 2 classes.
Found 5000 images belonging to 2 classes.


In [110]:
batch_size = 100

classifier.fit_generator(
    trainSet,
    steps_per_epoch = int(10000/batch_size),
    epochs = 5,
    validation_data = testSet,
    validation_steps = int(2500/batch_size)
)

Epoch 1/5
100/100 [==============================] - 13s 126ms/step - loss: 7.5865 - accuracy: 0.5025 - val_loss: 7.5293 - val_accuracy: 0.5063
Epoch 2/5
100/100 [==============================] - 12s 124ms/step - loss: 7.5913 - accuracy: 0.5022 - val_loss: 7.7009 - val_accuracy: 0.4950
Epoch 3/5
100/100 [==============================] - 13s 127ms/step - loss: 7.5960 - accuracy: 0.5019 - val_loss: 7.2434 - val_accuracy: 0.5250
Epoch 4/5
100/100 [==============================] - 13s 126ms/step - loss: 7.6532 - accuracy: 0.4981 - val_loss: 8.1012 - val_accuracy: 0.4688
Epoch 5/5
100/100 [==============================] - 12s 124ms/step - loss: 7.7628 - accuracy: 0.4909 - val_loss: 7.8534 - val_accuracy: 0.4850


In [111]:
import numpy as np

from keras.preprocessing import image

In [112]:
new_image = image.load_img(
    'test_image_2.jpg',
    target_size = (64, 64)
)

In [113]:
new_image = image.img_to_array(new_image)
new_image = np.expand_dims(new_image, axis = 0)

result = classifier.predict(new_image)
#trainSet.class_indices

if result[0][0] == 1:
    prediction = 'Dog'
else:
    prediction = 'Cat'
    
print(prediction)

Dog
