In [1]:
import cv2

ImportError: /home/bitai/anaconda3/bin/../lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var

In [1]:
!pip install opencv-python

In [7]:
!pip uninstall opencv-python

Found existing installation: opencv-python 4.3.0.36
Uninstalling opencv-python-4.3.0.36:
  Would remove:
    /home/bitai/anaconda3/lib/python3.7/site-packages/opencv_python-4.3.0.36.dist-info/*
    /home/bitai/anaconda3/lib/python3.7/site-packages/opencv_python.libs/libQtCore-6b7bca35.so.4.8.7
    /home/bitai/anaconda3/lib/python3.7/site-packages/opencv_python.libs/libQtGui-a00f4bbc.so.4.8.7
    /home/bitai/anaconda3/lib/python3.7/site-packages/opencv_python.libs/libQtTest-6d3ddc1c.so.4.8.7
    /home/bitai/anaconda3/lib/python3.7/site-packages/opencv_python.libs/libXcursor-1a09904e.so.1.0.2
    /home/bitai/anaconda3/lib/python3.7/site-packages/opencv_python.libs/libXfixes-d274cb03.so.3.1.0
    /home/bitai/anaconda3/lib/python3.7/site-packages/opencv_python.libs/libXi-e28fba09.so.6.1.0
    /home/bitai/anaconda3/lib/python3.7/site-packages/opencv_python.libs/libXinerama-b7a62e01.so.1.0.0
    /home/bitai/anaconda3/lib/python3.7/site-packages/opencv_python.libs/libXrandr-1b5fae8f.so.2.2.0


In [24]:
import cv2

In [27]:
help(cv2)

Help on package cv2:

NAME
    cv2

PACKAGE CONTENTS


FILE
    (built-in)




In [25]:
print(cv2.__version__)

AttributeError: module 'cv2' has no attribute '__version__'

In [1]:
import cv2

In [2]:
print(cv2.__version__)

4.3.0


In [3]:
import numpy as np

In [5]:
img = np.random.randint(0,10,(7,7))

print(img)

[[4 4 1 9 0 9 4]
 [9 1 8 3 1 3 2]
 [2 7 2 6 5 1 8]
 [8 0 7 6 7 7 1]
 [7 0 3 8 6 6 3]
 [9 1 5 0 8 6 2]
 [1 9 2 2 0 4 2]]


In [6]:
img_np = np.ones([7,7])
print(img_np)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [8]:
kernel = np.array([-1, 0, 1 ])
print(kernel)

[-1  0  1]


In [14]:
print(type(kernel))
print(type(img_np))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [18]:
img_cv = cv2.resize(img_np, (7,7))
                    
print(img_cv)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [17]:
kernel = cv2.resize(kernel, (1, 3))
print(kernel)

[[-1]
 [ 0]
 [ 1]]


In [21]:
print(type(img_cv))
print(type(kernel))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [23]:
conv_test = cv2.filter2D(img_cv, -1 , kernel)

print(conv_test)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [24]:
img_cv[0][0] = 0
img_cv[3][3] = 2
img_cv[6][6] = 3

conv_test = cv2.filter2D(img_cv, -1, kernel)

print(conv_test)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  2.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
