In [ ]:
# 0706

In [10]:
import numpy as np
vec1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(vec1)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
vec1 = np.arange(1, 11)
print(vec1)

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
mat1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]]
)
print(mat1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
mat2 = np.matrix([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]]
)
print(mat2)
print(mat2.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [14]:
mat3 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]]
)
print(mat3)

mat4 = np.array([
    [1,2,3],
    [4,5,6],
    [10,11,12]]
)
print(mat4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]]


In [15]:
mat5 = mat3 * mat4
print(mat5)

[[  1   4   9]
 [ 16  25  36]
 [ 70  88 108]]


In [16]:
# 행렬 연산의 규칙
# 행렬의 행과 열로 구성된다.
# 행렬의 곱셈을 수행하기 위한 최소한의 규칙
# m by n 행렬을 곱하려면 n by x가 되어야 한다.
# 두행렬의 곱셈 결과는 m by x가 된다.

In [17]:
print(mat1.T)
print("")
print(mat1)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [18]:
# 3  by 4 * 4 by 3 => 3 by 3
mat5 = mat1.T * mat2
print(mat5)

[[166 188 210]
 [188 214 240]
 [210 240 270]]


In [19]:
print(vec1.shape)

(10,)


In [20]:
smartMat = np.arange(0, 11, 2).reshape((2, 3))

print(smartMat)
print("")
print(smartMat.shape)

[[ 0  2  4]
 [ 6  8 10]]

(2, 3)


In [21]:
test = mat1 + 4
print(test)

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]]


In [22]:
smartMat2 = np.arange(1, 13).reshape((3, 4))

print(smartMat2)
print(smartMat2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [23]:
# 차원 변환이 필요한 경우가 있음 - 가우스-조르단 소거법

mat1 = mat1.reshape(12)

print(mat1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [24]:
print(len(mat1))

12


In [25]:
# 텐서를 해석하는 방법
# 맨 앞의 숫자가 큰 집합의 개수를 의미함
# 뒤쪽의 2개는 행렬의 모양을 의미
# 즉 뒤쪽에 2개를 통해 행렬의 모양을 잡고
# 맨 앞의 숫자를 통해 해당 행렬이 몇 개 있는지 파악하면 된다.
ten2 = mat1.reshape((3, 2, 2))

print(ten2)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [26]:
print(mat1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [27]:
ret = np.matrix(np.arange(1, 7)).reshape((2, 3))

ten3 = np.array([
    ret,  ret
])

print(ten3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [28]:
print(ten3.T)
print(ten3.T.shape)

[[[1 1]
  [4 4]]

 [[2 2]
  [5 5]]

 [[3 3]
  [6 6]]]
(3, 2, 2)


In [29]:
ten4 = ten2.dot(ten3)

print(ten4)

[[[[  9  12  15]
   [  9  12  15]]

  [[ 19  26  33]
   [ 19  26  33]]]


 [[[ 29  40  51]
   [ 29  40  51]]

  [[ 39  54  69]
   [ 39  54  69]]]


 [[[ 49  68  87]
   [ 49  68  87]]

  [[ 59  82 105]
   [ 59  82 105]]]]


In [35]:
testMat1 = np.arange(1, 5).reshape((2, 2))
testMat2 = np.arange(1, 5).reshape((2, 2))

print(testMat1)
print(testMat2)
print(testMat1 * testMat2)
print(testMat1.dot(testMat2))


[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [36]:
ten4 = ten2.dot(ten3)

print(ten4)

[[[[  9  12  15]
   [  9  12  15]]

  [[ 19  26  33]
   [ 19  26  33]]]


 [[[ 29  40  51]
   [ 29  40  51]]

  [[ 39  54  69]
   [ 39  54  69]]]


 [[[ 49  68  87]
   [ 49  68  87]]

  [[ 59  82 105]
   [ 59  82 105]]]]


In [38]:
# pip install tensorflow

In [40]:
from keras.models import Sequential

model = Sequential()

# 합성곱 = 콘볼루션(Convolution), 컨벌루션

In [41]:
#from keras.layers import Dense
#from keras.models import Sequential
#input_shape = 20
#units = 1
#model.add(Dense(units, input_dim=))

In [44]:
from keras.layers import Dense, Activation
from keras.models import Sequential
input_shape = 20
units = 1
model.add(Dense(units, input_dim = input_shape))
model.add(Activation('tanh'))